import Head from "next/head";
import Brand from "../components/Brand";

export default function Home() {
  return (
    <>
      <Head>
        <title>Auth Concept</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section className="flex justify-center">
        <h2 className="max-w-sm">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore
          dignissimos facilis odio. Distinctio enim quisquam exercitationem
          culpa omnis ab eos.
        </h2>
      </section>
      <Brand />
    </>
  );
}
